version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgresdb
    env_file: ./code-task.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - db-network

  api:
    image: zehd/task:latest
    #build: .
    env_file: ./code-task.env
    #labels:
    # - "traefik.enable=true"
    # - "traefik.http.routers.scm.rule=Host(`task.poniatowski.dev`)"
    # - "traefik.http.routers.scm.entrypoints=websecure"
    # - "traefik.http.routers.scm.tls.certresolver=letsencrypt"
    # - "traefik.http.services.scm.loadbalancer.server.port=8080"
    # - "traefik.docker.network=proxy"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - db-network
      #- proxy

networks:
  #proxy:
  # name: proxy
  # external: true
  db-network:
    driver: bridge
    external: false
